name: SC-Open.dev
url: https://www.sc-open.dev
title: SC-Open.dev
timezone: America/New_York
layouts_dir: _layouts
author_name: "SC-Open.dev"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"