name: SC-Open.dev
url: https://www.sc-open.dev
timezone: America/New_York
theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: SC-Open.dev
description: Collaboration Accelerator for Star Citizen Community Developers
layouts_dir: _layouts
author_name: "SC-Open.dev"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
