timezone: America/New_York
layouts_dir: _layouts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author_name: "SC-Open.dev"